//  set_ip.h : précisions sur l'implantation du module set.

//  set_empty : temps ... ; espace ...
//  set_dispose : temps ... ; espace ...
//  set_add : temps ... ; espace ...
//  set_remove : temps ... ; espace ...
//  set_pick : temps ... ; espace ...
//  set_is_in : temps ... ; espace ...
//  set_is_empty : temps ... ; espace ...
//  set_card : temps ... ; espace ...

//#define SET_EXT

//  set_min : temps ... ; espace ...
